name: cb
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pip
  - pip:
    - git+https://github.com/patrickmineault/sphinx-book-theme.git
    - git+https://github.com/executablebooks/jupyter-book.git
    - tqdm
    - sphinxext-opengraph